version: "3.8"

services:
  react-app-dev:
    build:
      context: .
      target: development
    container_name: react-app-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true # Required for React interactive mode
    tty: true

  # Production environment
  react-app-prod:
    build:
      context: .
      target: production
    container_name: react-app-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
